### ISSUE TITLE
ask for advice

### ISSUE THREAD

**Issue by HBdingdang** [Azeved00/cpp-decision-tree#1]
I use VS2022 compiler to compile code, prompting multiple definitions. What should I do about this?

**Comment by Azeved00** [comment]
Hello @HBdingdang,

I do not know what you mean by prompting multiple definitions.
To compile & run the project I used the commands that i put in the `README.md`.
If you give me more information on the issue you are getting, (like screen shots and error codes/messages), i can look more into it and help you!

Good Luck!

**Comment by HBdingdang** [comment]
This problem has been solved and can be compiled normally. Thank you for your guidance and excellent code.

**Comment by Azeved00** [comment]
Glad to hear that!
